demodev-lab/demo-funnel

- app/admin/layout.tsx
- components/admin/sidebar.tsx
> style: 서비스 이름 수정

- app/admin/challenges/page.tsx
- components/admin/sidebar.tsx
> 
> 어드민 페이지에 챌린지 관리 기능 추가했습니다.
>
> feat: 어드민 페이지 챌린지 관리 기능 추가

- app/page.tsx
> ex) #이슈번호, #이슈번호
> 사용자 페이지 서비스 이름 수정했습니다.
>
> style: 사용자 페이지 서비스 이름 수정

- .github/workflows/build.yml
>
> GitHub Actions 워크플로우 파일 추가했습니다.
>
> chore: GitHub Actions 워크플로우 설정 추가

- app/admin/login/actions.ts
- app/admin/login/page.tsx
- app/admin/signup/page.tsx
> 
> 어드민 페이지 회원가입 시 성공 여부를 알려주는 모달 추가하였습니다.
- 회원가입 성공
- 회원가입 실패
> 실패 시 모달에 표시되는 내용은 추후 수정이 필요합니다.
> feat: 회원가입 성공 여부를 알려주는 모달 추가

- app/admin/lectures/page.tsx
- components/admin/lecture-form.tsx
>
> - admin [강의관리]의 강의 추가 모달에 폼 필드 수정했습니다.
> - [x] '오픈 날짜' 필드를 제거하고 '챌린지 선택' 필드로 변경
> - [x] '과제' 입력 필드 추가
>
> 추가로 해당 작업으로 인해 모달창의 height가 길어져 화면밖으로 나가는 이슈가 있어 ui 수정하고 등록버튼의 경우 모달 하단에 고정되게 수정하였습니다.
>
> feat: admin 강의 추가 모달 폼 필드 수정 (챌린지 선택, 과제 필드 추가)

- apis/users.ts
- package.json
- pnpm-lock.yaml
- tsconfig.json
> 
> Supabase REST API 호출용 getUsers 함수 예시로 작성해서 추가했습니다.
> @dohyeons @wynter24 일단 예시로 작성했는데 두분 스타일에 맞춰서 수정하고 다른 api 호출 함수들도 정의하시면 될 것 같습니다. 🙇‍♀️
> feat: Supabase REST API 호출용 getUsers 함수 추가

- app/admin/(dashboard)/students/page.tsx
- app/api/students/[id]/route.ts
- app/api/students/route.ts
- app/layout.tsx
- components/admin/student-list.tsx
- hooks/useStudents.ts
- lib/data/students-data.ts
- lib/providers/react-query-provider.tsx
- package.json
- pnpm-lock.yaml
> #17 #18 
> 수강생 crud
> mock data로 작성되었습니다. 컴포넌트 분리도 안되어있으며 실제 api와 연결한 기능 구현 후 분리할게요.
> Feat/main/student crud #17

- app/layout.tsx
- components/daily-lecture-player/daily-lecture-section.tsx
- components/daily-lecture-player/lecture-player.tsx
- components/demo-ui.tsx
- lib/msw/browser.ts
- lib/msw/handlers.ts
- lib/msw/handlers/index.ts
- lib/msw/handlers/lecture/get-lectures.ts
- lib/msw/handlers/lecture/index.ts
- lib/msw/mock-provider.tsx
- lib/msw/msw-bootstrap.tsx
- package-lock.json
- package.json
- pnpm-lock.yaml
- public/mockServiceWorker.js
> ex) #30 #23
> MSW 세팅 및 동영상 목록 가져오기 API 로직 구현
백엔드 API 구축 이전에, 프론트 단에서 api 로직을 먼저 작성하기 위해 MSW를 설치했습니다.
⭐.env 파일에 아래 코드를 추가해주세요!
```js
NEXT_PUBLIC_API_MOCKING=enabled
```
1. `lib>msw>handlers`에서 각 페이지 혹은 기능 별로 폴더를 정의하고 api를 정의합니다.
2. `handlers>index.ts`에 해당 api를 호출합니다.
3. 컴포넌트에서 msw에 설정한 경로로 api를 호출합니다. 
(msw를 연결한 상태에서 api를 호출할 경우 실제 api 연결을 가로채기 때문에, 추후 api 경로만 수정하면 됩니다.)
4. 터미널에서 `pnpm run dev:msw` 를 입력하여 msw 실행시켜 브라우저에서 정상 동작하는지 확인합니다.
(`pnpm run dev`는 msw 없이 기존 서버와 연동되어 실행됩니다)
상세한 코드는 해당 파일 참고 부탁드립니다!
> feat: MSW 세팅 및 동영상 목록 가져오기 기능 추가

- apis/users.ts
- hooks/useStudents.ts
> 
> - 기존 axios 호출하던 방식에서 Supabase SDK 방식으로 전환했습니다.
>
> refactor: 수강생 API 호출 함수 및 커스텀 훅 수정

- apis/challenges.ts
- apis/users.ts
- app/admin/(dashboard)/challenges/page.tsx
- components/admin/student-list.tsx
> #14 
> 챌린지 crud 구현하고 엑셀 업로드 재구현했습니다.
> challenges crud

- apis/lectures.ts
- app/admin/(dashboard)/lectures/page.tsx
- components/admin/lecture-form.tsx
> ex) #10
> 강의 crud 구현했습니다.(구현 안된 파일 업로드, 과제 제외)
> 강의 crud 구현

- components/admin/header.tsx
> ex) #21 
> 헤더에 있는 드롭다운에 challenges api 연동했습니다.
> 헤더에 챌린지(기수) 정보 연동

- apis/auth.ts
> 
> - 이메일을 기반으로 사용자 정보를 조회하는 userLogin 함수 추가
> - Supabase의 Users 테이블에서 이메일로 검색하여 사용자 정보(id, name, email)를 반환
>
> feat: 이메일 기반 사용자 로그인 함수 추가

- apis/lectures.ts
- app/admin/(dashboard)/lectures/page.tsx
- components/admin/lecture-form.tsx
> #21 
> 기수별로 강의 불러오는 기능을 구현하고 수정, 삭제 시 발생하는 에러를 해결했습니다.
> 기수별 강의 관리 기능 구현 및 에러 수정

- apis/assignments.ts
- apis/challenges.ts
- apis/lectures.ts
- apis/users.ts
- app/admin/(dashboard)/challenges/page.tsx
- app/admin/(dashboard)/lectures/page.tsx
- components/admin/header.tsx
- components/admin/lecture-form.tsx
- hooks/useStudents.ts
- lib/store/useChallengeStore.ts
> 
> - 기존에는 id 값을 문자열(string)로 처리하고 있었으나, Supabase에서 해당 필드는 기본적으로 숫자(number) 타입이므로 타입 불일치로 인한 잠재적인 오류 가능성이 있었습니다. 이에 따라 타입을 수정하는 작업했습니다. (모든 파일들을 작업하지 못했습니다. 추후 코드들 정리하면서 남은 코드들 작업하겠습니다.)
> 해당 작업으로 인해 예상치 못한 사이드 이펙트가 있을 수 있습니다. 각자 수정해주시면 감사하겠습니다...🥹
> fix: API 호출 함수들 id 기반 인자 타입을 string → number로 수정

- apis/challenges.ts
- apis/users.ts
- app/admin/(dashboard)/challenges/page.tsx
- app/admin/(dashboard)/course-info/page.tsx
- app/admin/(dashboard)/email/page.tsx
- app/admin/(dashboard)/layout.tsx
- app/admin/(dashboard)/lectures/page.tsx
- app/admin/(dashboard)/page.tsx
- app/admin/(dashboard)/students/page.tsx
- components/admin/course-info-table.tsx
- components/admin/header.tsx
- components/admin/student-list.tsx
- hooks/useStudents.ts
> #12 
> 수강 정보 조회 기능을 구현했고, header가 어드민의 각 페이지마다 렌더링되고 있어서.. layout.tsx로 통합시켰습니다.
민주님이 말씀주신 type error도 해결했습니다.
> 수강 정보 조회 구현

- apis/lectures.ts
- app/admin/(dashboard)/lectures/page.tsx
- components/admin/lecture-form.tsx
> ex) #이슈번호, #이슈번호
> - 어드민 페이지 강의 관리에서 동영상 업로드, 미리보기 기능 추가하였습니다.
>
> feat: 강의 관리에서 동영상 업로드, 미리보기 기능 추가

- apis/lectures.ts
> 
> - 어드민 페이지에서 강의 수정, 삭제 시 Supabase storage 파일도 삭제하는 로직 추가했습니다.
>
> refactor: 강의 수정, 삭제 시 Supabase storage 파일도 삭제하는 로직 추가

- apis/assignments.ts
> 과제 제출 시 시간 비교 로직 구현

- apis/lectures.ts
> 
> - getUserLectures 함수의 날짜 비교 로직 서버 시간 기준으로 비교되게 수정하였습니다.
> - 추가로 강의 목록을 가져올 때 open_at 오름차순으로 가져오게 수정하였습니다.
>
> fix: getUserLectures 함수 서버 시간 기준 날짜 비교로 수정

- apis/lectures.ts
- app/admin/(dashboard)/lectures/page.tsx
- components/admin/lecture-form.tsx
- constants/uploadTypes.ts
- types/lecture.ts
- utils/auth.ts
- utils/files.ts
> 
> - 강의 API 호출 함수 파일 내 타입과 공통 로직 분리하였습니다.
>
> refactor: 강의 API 타입 및 공통 로직 분리

- apis/users.ts
- hooks/useStudents.ts
- types/user.ts
> refactor: 유저 관련 타입들 분리

- .github/workflows/build.yml
- apis/__tests__/challenges.test.ts
- apis/challenges.ts
- components/admin/lecture-form.tsx
- jest.config.ts
- jest.setup.ts
- package.json
- pnpm-lock.yaml
- utils/errorHandler.ts
> 
> - 챌린지 API 호출 함수의 반복되는 에러처리를 유틸함수로 분리했습니다. (추후 다른 함수들도 적용하겠습니다.)
> - 챌린지 API 호출 함수 테스트코드 작성했습니다.
>
> refactor: 챌린지 API 호출 함수 에러핸들링 분리 및 테스트코드 작성

- .github/workflows/build.yml
- .gitignore
- app/admin/(dashboard)/challenges/page.test.tsx
- app/admin/(dashboard)/course-info/pege.test.tsx
- app/admin/(dashboard)/lectures/page.test.tsx
- app/admin/(dashboard)/lectures/page.tsx
- app/admin/(dashboard)/students/page.test.tsx
- components/admin/student-list.tsx
- jest.config.ts
- package.json
- pnpm-lock.yaml
- test/__mocks__/fileMock.js
- tsconfig.jest.json
> #79 
> 어드민 페이지의 테스트 코드를 작성했습니다.
> 어드민 페이지 테스트 구현

- apis/users.ts
- components/admin/student-list.tsx
- hooks/useStudents.ts
> Refactor/main/component refactoring #62

- components/admin/email-sender.tsx
> ex) #이슈번호, #이슈번호
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
> fix: 확인용 수정

- app/api/email/route.ts
- components/admin/email-sender.tsx
- constants/email-templates.ts
> 이메일 템플릿 변경

- components/daily-assignment/assignment-submission-section.tsx
- components/daily-lecture/daily-lecture-section.tsx
> #101
> 과제 마감시 마감 안내 문구 추가, 메인 강의 로딩 추가
> [Design] 서비스페이지 과제 마감 안내 및 메인 강의 로딩 추가

- app/class/page.tsx
- components/daily-assignment/assignment-confetti.tsx
- components/daily-assignment/assignment-submission-form.tsx
- components/daily-assignment/assignment-submission-section.tsx
- components/daily-lecture/daily-lecture-section.tsx
- components/icons/ic-email.tsx
- components/icons/ic-loading-spinner.tsx
- components/icons/index.ts
- components/login-form.tsx
- package.json
- pnpm-lock.yaml
> #114
> 첫 렌더링 시 오늘 강의 표시, 제출 및 강의 선택 로딩 추가, 로그인 성공 안내 표시 개선, 과제 제출 성공 confetti 효과 추가 
**과제 제출 후 효과 추가**
(테스트를 위한 버튼으로 테스트용 버튼은 삭제하고 과제 제출 성공 시에만 해당 효과가 보이도록 했습니다)
https://github.com/user-attachments/assets/6c0386c1-4325-4fa5-8e90-e79603530ac9
**로그인 성공**
https://github.com/user-attachments/assets/f2f5caf4-ee8a-4842-b1f5-7fb35149c1e0
-`components\daily-assignment\assignment-confetti.tsx` 에서 크기 및 디자인을 커스텀 할 수 있어요!
보시고 편하게 수정하시면 됩니다.
- 현재 매 과제 제출마다 효과가 나타나고 있는데 추후 환급 버튼이 추가 된다면 최종 과제 제출 또는 환급 버튼 클릭 시에만 해당 효과를 보여주는 게 더 극적일 것 같다는 생각이 드네요🤔
추후 기능 추가하면서 이 점도 함께 고려해보면 좋을 것 같아요!
> design: 애니메이션 및 로딩 UX 개선

- components/admin/course-info-table.tsx
> ex) #127 
> 레이아웃이 깨지는 문제가 있어서 간단하게 수정했습니다...!
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
> course-info 레이아웃 수정

- apis/assignments.ts
- apis/users.ts
- components/admin/course-info-table.tsx
- types/user.ts
> #112 
> admin에서 과제 제출하고 수정하고 삭제하는 기능 구현했습니다..!
> 어드민에서 과제 제출, 수정, 삭제 구현

- components/admin/course-info-table.tsx
- components/admin/course-info/StudentTable.tsx
- components/admin/course-info/SubmissionDialogContent.tsx
- components/admin/course-info/SubmissionForm.tsx
> #112 
> 모달 깜빡거림 삭제하고 코드가 너무 길어져서 리팩토링 조금 진행했습니다.
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
> 수강 관련 페이지 수정 사항

- apis/users.ts
> #139
- 기존 수강생이 새로운 챌린지에 등록될 수 있도록 createUser 함수 수정
> [수강생 추가] 버튼을 눌러 수강생을 등록할 때, 이미 등록된 수강생인 경우, 새로운 챌린지에 추가 등록이 불가능하며, 신규 챌린지에 포함시키기 위해선 기존 데이터를 직접 수정해야 하는 비효율적인 플로우였습니다. 이를 해결하기 위해 createUser 함수의 로직을 수정했습니다.
>
> fix: 기존 수강생이 새로운 챌린지에 등록될 수 있도록 createUser 함수 수정

- middleware.ts
> 
- /class 경로 접근 시 /login으로 리디렉션 처리되도록 미들웨어 수정했습니다.
> 루트 경로에 랜딩 페이지가 추가되어서, 앞으로 수강생들에겐 /class 경로로 안내해드리기 위해 미들웨어 수정했습니다.
>
> feat: /class 경로 접근 시 /login으로 리디렉션 처리되도록 미들웨어 수정

- app/class/[challengeId]/page.tsx
- components/class/ClassPage.tsx
- hooks/class/useClassPage.ts
> 
- 사용자 페이지에서 selectedLecture가 undefined일 때 발생하는 런타임 에러 수정
> 
>
> fix: selectedLecture가 undefined일 때 발생하는 런타임 에러 수정

- apis/lectures.ts
- components/class/DailyLectureItem.tsx
> 
- 로컬에선 강의 잠금처리가 정상적으로 작동하는데 배포환경에선 잘 안되는 것 같아 확인용 콘솔 추가합니다.
> 간단한 콘솔만 추가했기때문에 직접 머지하고 해당 이슈 파악하겠습니다.
> fix: 배포환경 디버깅을 위한 콘솔 추가

- apis/lectures.ts
- hooks/class/useClassPage.ts
> fix: 배포환경 이슈 해결을 위한 캐시 시간 수정

- components/class/AssignmentSubmissionForm.tsx
- components/class/AssignmentSubmissionSection.tsx
- components/class/ClassPage.tsx
>
- 마지막 과제 제출 시 .vercel.app 도메인이 포함된 링크는 제출이 불가능하도록 유효성 검사 로직을 추가했습니다.
> 일단 급하게 프론트단에서 수정하였습니다. 추후 db 구조 수정이 필요합니다.
>
> feat: 마지막 과제의 경우 링크 유효성 검사 추가

- components/class/AssignmentSubmissionSection.tsx
> 
- 마지막 강의의 과제인 경우 환급안내문 추가했습니다.
> 빠른 적용을 위해 하드코딩으로 작업해놨습니다. 다음주 챌린지 진행 전까지 https://github.com/demodev-lab/demodev-lecture 와 연결 필요합니다.
>
> feat: 마지막 강의의 과제 환급안내문 추가
